### ISSUE TITLE
Herokuapp Application error

### ISSUE THREAD

**Issue by ElersonSoares** [heivo/gt-team-planner#2]
Hi.
Herokuapp Application error.
Do you intend to continue to update the project?

Thanks.

**Comment by heivo** [comment]
Hi,

I didn't update the app for more than a year and don't plan to do so as I'm not playing the game anymore.

Heroku discontinued the free hosting, that's why there is this error. I can try to deploy it somewhere else but it's probably not very helpful because it's so outdated.

**Comment by ElersonSoares** [comment]
Hi.
I'm glad you answered me.

Since you no longer play the game, you don't have to worry about posting the application.

If I had knowledge I would do it myself.

The Guardian Tales community was in need of a high level Party Build like yours, as the one we had is no longer available.

Do you have any suggestions on how I can make one?

**Comment by heivo** [comment]
I'm afraid this is nothing that I can answer in a few sentences. It requires some programming and web technology skills.

**Comment by heivo** [comment]
I have deployed it on fly.io, it's now available again at https://gt-team-planner.fly.dev/
